-- Bascule la session vers la base pluggable XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;

-- Attribue les privilèges nécessaires au développement
GRANT CREATE SESSION,      -- Autorise la connexion à la base
      CREATE TABLE,        -- Autorise la création de tables
      CREATE VIEW,         -- Autorise la création de vues
      CREATE SEQUENCE,     -- Autorise la création de séquences
      CREATE TRIGGER       -- Autorise la création de triggers
TO TP3;

-- =====================================================
-- CLEAN DROP (optional – safe drop)
-- Suppression sécurisée des tables existantes
-- =====================================================

-- Supprime la table SIGNATURE si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE signature CASCADE CONSTRAINTS';
EXCEPTION
  -- Ignore l'erreur si la table n'existe pas
  WHEN OTHERS THEN NULL;
END;
/

-- Supprime la table PETITION si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE petition CASCADE CONSTRAINTS';
EXCEPTION
  -- Ignore l'erreur si la table n'existe pas
  WHEN OTHERS THEN NULL;
END;
/

-- Supprime la table USERS si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
  -- Ignore l'erreur si la table n'existe pas
  WHEN OTHERS THEN NULL;
END;
/

-- =====================================================
-- TABLES CREATION
-- Définition des structures de données
-- =====================================================

-- USERS TABLE : stocke les informations des utilisateurs
CREATE TABLE users (
  -- Identifiant unique de l'utilisateur (clé primaire)
  id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Adresse email de l'utilisateur (unique et obligatoire)
  email    VARCHAR2(255) NOT NULL UNIQUE,
  -- Mot de passe de l'utilisateur (obligatoire)
  password VARCHAR2(255) NOT NULL,
  -- Nom de famille de l'utilisateur
  nom      VARCHAR2(100) NOT NULL,
  -- Prénom de l'utilisateur
  prenom   VARCHAR2(100) NOT NULL,
  -- Pays de résidence de l'utilisateur
  pays     VARCHAR2(100) NOT NULL
);

-- PETITION TABLE : stocke les informations des pétitions
CREATE TABLE petition (
  -- Identifiant unique de la pétition (clé primaire)
  IDP          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Titre de la pétition
  TitreP       VARCHAR2(200) NOT NULL,
  -- Description détaillée de la pétition
  DescriptionP CLOB NOT NULL,
  -- Date d'ajout de la pétition
  DateAjoutP   DATE NOT NULL,
  -- Date de fin de la pétition
  DateFinP     DATE NOT NULL,
  -- Nom du porteur de la pétition
  NomPorteurP  VARCHAR2(200) NOT NULL,
  -- Email du porteur de la pétition
  Email        VARCHAR2(255) NOT NULL
);

-- SIGNATURE TABLE : stocke les signatures des pétitions
CREATE TABLE signature (
  -- Identifiant unique de la signature (clé primaire)
  IDS      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Référence à la pétition signée
  IDP      NUMBER NOT NULL,
  -- Nom du signataire
  NomS     VARCHAR2(120) NOT NULL,
  -- Prénom du signataire
  PrenomS  VARCHAR2(120) NOT NULL,
  -- Pays du signataire
  PaysS    VARCHAR2(120) NOT NULL,
  -- Date de la signature
  DateS    DATE NOT NULL,
  -- Heure de la signature
  HeureS   VARCHAR2(8) NOT NULL,
  -- Email du signataire
  EmailS   VARCHAR2(255) NOT NULL,
  -- Contrainte de clé étrangère liant la signature à une pétition
  CONSTRAINT fk_signature_petition
    FOREIGN KEY (IDP)
    REFERENCES petition(IDP)
    -- Supprime automatiquement les signatures si la pétition est supprimée
    ON DELETE CASCADE
);

-- Index pour accélérer les recherches par pétition dans SIGNATURE
CREATE INDEX idx_signature_idp ON signature(IDP);

-- Index pour accélérer les recherches par date d'ajout des pétitions
CREATE INDEX idx_petition_date ON petition(DateAjoutP);
