-- =====================================================
-- TP3 Database Setup Script
-- Oracle XE (XEPDB1)
-- =====================================================

-- Switch to pluggable database
ALTER SESSION SET CONTAINER = XEPDB1;

-- =====================================================
-- USER CREATION
-- =====================================================

CREATE USER TP3 IDENTIFIED BY tp3
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE SEQUENCE,
      CREATE TRIGGER
TO TP3;

-- =====================================================
-- CLEAN DROP (optional – safe drop)
-- =====================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE signature CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE petition CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- =====================================================
-- TABLES CREATION
-- =====================================================

-- USERS TABLE
CREATE TABLE users (
  id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email    VARCHAR2(255) NOT NULL UNIQUE,
  password VARCHAR2(255) NOT NULL,
  nom      VARCHAR2(100) NOT NULL,
  prenom   VARCHAR2(100) NOT NULL,
  pays     VARCHAR2(100) NOT NULL
);

-- PETITION TABLE
CREATE TABLE petition (
  IDP          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TitreP       VARCHAR2(200) NOT NULL,
  DescriptionP CLOB NOT NULL,
  DateAjoutP   DATE NOT NULL,
  DateFinP     DATE NOT NULL,
  NomPorteurP  VARCHAR2(200) NOT NULL,
  Email        VARCHAR2(255) NOT NULL
);

-- SIGNATURE TABLE
CREATE TABLE signature (
  IDS      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IDP      NUMBER NOT NULL,
  NomS     VARCHAR2(120) NOT NULL,
  PrenomS  VARCHAR2(120) NOT NULL,
  PaysS    VARCHAR2(120) NOT NULL,
  DateS    DATE NOT NULL,
  HeureS   VARCHAR2(8) NOT NULL,
  EmailS   VARCHAR2(255) NOT NULL,
  CONSTRAINT fk_signature_petition
    FOREIGN KEY (IDP)
    REFERENCES petition(IDP)
    ON DELETE CASCADE
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX idx_signature_idp ON signature(IDP);
CREATE INDEX idx_petition_date ON petition(DateAjoutP);

-- =====================================================
-- END OF SCRIPT
-- =====================================================
